

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fen
 */
public class Row extends javax.swing.JFrame {

    /**
     * Creates new form row
     */
    protected String [] columnNames;
    
    public Row() throws SQLException {
        initComponents();
        columnNames=Database.getColumnNames((String)Database.cbTables.getSelectedItem());
        addRow.setModel(new DefaultTableModel(columnNames, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        addRow = new javax.swing.JTable();
        btnCommit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addRow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(addRow);

        btnCommit.setText("Commit");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnCommit)
                        .addGap(75, 75, 75)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCommit)
                    .addComponent(btnCancel))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        try {
            // TODO add your handling code here:
            int columnCount=columnNames.length;
          
            ResultSetMetaData metaData = Database.getMetaData();
            
            String query="INSERT INTO "+(String)Database.cbTables.getSelectedItem()+" VALUES (";
            for(int i=0;i<columnCount;i++)
            {
                if(metaData.getColumnType(i+1)==Types.CHAR ||  metaData.getColumnType(i+1)==Types.DATE || metaData.getColumnType(i+1)==Types.VARCHAR)
                {     
                query+="'";
                query+=addRow.getModel().getValueAt(0, i);
                query+="'";
                }
                else
                    query+=(String)addRow.getModel().getValueAt(0, i);
                
                if(i!=columnCount-1)
                    query+=",";
            }
            query+=")";

            Statement st=Database.connection.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM "+(String)Database.cbTables.getSelectedItem());
            
            st.executeUpdate(query);
            
            rs=st.executeQuery("SELECT * FROM "+(String)Database.cbTables.getSelectedItem());
            View.table.setModel(View.resultsetToTableModel(rs));
        }
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(this,e+"\n Please re-enter.");
            try 
            {
                Row r=new Row();
                r.setVisible(true);
                this.dispose();
            }
            catch (SQLException ex) {
                Logger.getLogger(Row.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        
        this.dispose();
        
    }//GEN-LAST:event_btnCommitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable addRow;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCommit;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
